feat: add Ansible bootstrap

diff --git a/scripts/run_once_install.sh.tmpl b/scripts/run_once_install.sh.tmpl
--- a/scripts/run_once_install.sh.tmpl
+++ b/scripts/run_once_install.sh.tmpl
@@ -6,13 +6,26 @@
 #                                     \//_/
 #
 #                          X N L I - W o r k s p a c e
-#                      Chezmoi - Required tools installer
+#                      Chezmoi - Environment installer
 #
 # -----------------------------------------------------------------------------
 
 {{ if eq .chezmoi.os "linux" -}}
 # --- Install package for Linux
 # -----------------------------------------------------------------------------
+{{ $pkg_script := (printf "./scripts/install-requirements/linux_%s_%s" .chezmoi.osRelease.id .chezmoi.arch) }}
+{{ if stat $pkg_script }}
 echo "> Install required package for your system ({{ .chezmoi.osRelease.prettyName }} - {{ .chezmoi.arch }})"
-{{      include (printf "./scripts/install-package/%s_%s_%s" .chezmoi.os .chezmoi.osRelease.id .chezmoi.arch ) }}
-{{ end -}}
+{{      include $pkg_script }}
+{{ else }}
+echo >&2 {{ printf "! Failed to find package installer for %s (%s (%s))" .chezmoi.osRelease.prettyName .chezmoi.osRelease.id .chezmoi.arch }}
+exit 1
+{{ end }}
+{{ else }}
+echo >&2 {{ printf "! OS %s is currently cannot be managed by `chezmoi`" .chezmoi.os }}
+{{ end }}
+
+# --- Run Ansible to install other requirements
+# -----------------------------------------------------------------------------
+
+
